import { InputTypes } from "./sharedFunctions";

export const defaultInputValues: InputTypes = {
    calculationType: "Fixed Interval",
    stepSize: 0.01,
    innerGeometryShape: "Sphere",
    innerGeometryRadius1: 4,
    innerGeometryRadius2: 1,
    outerGeometryShape: "Sphere",
    outerGeometryRadius: 1,
    dEqualsOuterGeometryRadius: true,
    dLineRadius: 1,
    curveTheta: "2t",
    curvePhi: "t",
    curveTRange: [-10, 40],
    curveTStart: -10,
};

export const minTRange = 20;
export const tMin = -200;
export const tMax = 200;

export const defaultInputValueConstraints = {
    stepSizeRange: [0.01, 0.1],
    innerGeometryRadius1Range: [0.25, 6],
    innerGeometryRadius2Range: [0.25, 6],
    outerGeometryRadiusRange: [0.1, 10],
    dLineRadiusRange: [0.1, 10],
    curveTRangeRange: [tMin, tMax],
    curveTStartRange: [tMin, tMax - minTRange],
};

export const defaultStyleValues = {
    backgroundColor: "#171717",
    innerGeometryVisible: true,
    innerGeometryMaterial: "MeshStandardMaterial",
    innerGeometryColor: "#100e19",
    innerGeometryEmissive: "#070808",
    innerGeometryEmissiveIntensity: 0.4,
    innerGeometryMetalness: 0.62,
    innerGeometryRoughness: 0.16,
    innerGeometryFlatShading: true,
    innerGeometryWireframe: false,
    outerGeometryVisible: true,
    outerGeometryMaterial: "MeshStandardMaterial",
    outerGeometryColor: "#100e19",
    outerGeometryEmissive: "#070808",
    outerGeometryEmissiveIntensity: 0.4,
    outerGeometryMetalness: 0.62,
    outerGeometryRoughness: 0.16,
    outerGeometryFlatShading: true,
    outerGeometryWireframe: false,
    dLineVisible: true,
    dLineWidth: 0.02,
    dLineMaterial: "MeshStandardMaterial",
    dLineColor: "#d5d4e3",
    dLineEmissive: "#d2e0de",
    dLineEmissiveIntensity: 1.3,
    dLineMetalness: 0.56,
    dLineRoughness: 0.18,
    dLineFlatShading: false,
    dLineWireframe: false,
    dPointVisible: true,
    dPointRadius: 0.05,
    dPointMaterial: "MeshStandardMaterial",
    dPointColor: "#d5d4e3",
    dPointEmissive: "#d2e0de",
    dPointEmissiveIntensity: 1.3,
    dPointMetalness: 0.56,
    dPointRoughness: 0.18,
    dPointFlatShading: false,
    dPointWireframe: false,
    curveVisible: true,
    curveDrawType: "From Start Point",
    curveColor: "#ffffff",
    curveWidth: 0.05,
    curveTrailLength: 500,
    curveTrailDecay: 0.01,
};

export const defaultLightValues = {
    ambientEnabled: true,
    ambientIntensity: 1.0,
    ambientColor: "#ffffff",
    directionalLightEnabled: true,
    directionalLightIntensity: 0.6,
    directionalLightColor: "#ffffff",
    directionalLightPosition: [0, 0, 20],
    lightformer1Enabled: true,
    lightformer1Form: "ring",
    lightformer1Intensity: 2.1,
    lightformer1Color: "#fdf9ff",
    lightformer1Scale: 31,
    lightformer1Position: [0, 0, 20],
    lightformer2Enabled: true,
    lightformer2Form: "circle",
    lightformer2Intensity: 0.2,
    lightformer2Color: "#fdf9ff",
    lightformer2Scale: 56,
    lightformer2Position: [0, 0, -20],
    lightformer3Enabled: false,
    lightformer3Form: "circle",
    lightformer3Intensity: 0.4,
    lightformer3Color: "#50bdff",
    lightformer3Scale: 32,
    lightformer3Position: [10, 10, 5],
};
